#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_GF3258_FINGERPRINT) += gf3258/
obj-$(CONFIG_GF3658_FINGERPRINT) += gf3658/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
obj-$(CONFIG_FPC_REE_FINGERPRINT) += fpc_ree/
obj-$(CONFIG_FINGERPRINT_FPSENSOR_JC_TEE) += fpsensor_jc_tee/
obj-$(CONFIG_FINGERPRINT_MICROARRAY_FP) += microarray/
obj-$(CONFIG_FINGERPRINT_BLESTECH) += betterlife/
obj-$(CONFIG_MTK_FINGERPRINT_SUNWAVECORP) += sunwave_fp/
obj-$(CONFIG_FINGERPRINT_SUNWAVE_FP_TEE) += sunwave_fp_tee/
