#
# Makefile for Miramems Motion Sensor driver
#
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/accelerometer/inc
ccflags-y += -I$(srctree)/drivers/misc/mediatek/sensors-1.0/hwmon/include


obj-y	:= mir3da_core.o  mir3da_cust.o
