# Linux driver folder
ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/GT1XX/
ccflags-y += -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/touchpanel/GT1XX/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT1XX/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GT1XX/include/firmware1/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

obj-y	+=  gt1x_extents.o gt1x_generic.o gt1x_tools.o gt1x_tpd.o gt1x_update.o

