ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include/mt-plat/$(MTK_PLATFORM)/include/

#obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone-tddi.o

obj-y +=  cts_tpd_driver.o
obj-y +=  cts_i2c_driver.o
obj-y +=  cts_core.o
obj-y +=  cts_platform.o
obj-y +=  cts_sfctrlv2.o
obj-y +=  cts_spi_flash.o
obj-y +=  cts_firmware.o
obj-y +=  cts_tool.o
obj-y +=  cts_sysfs.o
obj-y +=  cts_test.o

