# Stoneoim:yucheng on: Sat, 15 Oct 2016 17:18:22 +0800
# this is a example to add a hall

#below is a example
# Linux driver folder
#ccflags-y += -I$(srctree)/drivers/misc/mediatek/mach/$(MTK_PLATFORM)/$(ARCH_MTK_PROJECT)/hall/dummy_hall/
obj-y	+=  dummy.o
# End of Stoneoim: yucheng

